---
version: 2
updates:
  # main branch
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/api"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/tools"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
