apiVersion: apps/v1
kind: Deployment
metadata:
  name: percona-version-service
spec:
  replicas: 3
  selector:
    matchLabels:
      name: percona-version-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: percona-version-service
    spec:
      containers:
      - env:
        - name: SERVE_HTTP
          value: "true"
        image: perconalab/version-service:master-8ac1b21
        imagePullPolicy: Always
        name: percona-version-service
        ports:
        - containerPort: 11000
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: percona-version-service
  name: percona-version-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 11000
  selector:
    name: percona-version-service
  type: ClusterIP
