// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/version.proto

package version

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status describes the current version status.
type Status int32

const (
	Status_status_invalid Status = 0
	Status_recommended    Status = 1
	Status_available      Status = 2
	Status_required       Status = 3
	Status_disabled       Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "status_invalid",
		1: "recommended",
		2: "available",
		3: "required",
		4: "disabled",
	}
	Status_value = map[string]int32{
		"status_invalid": 0,
		"recommended":    1,
		"available":      2,
		"required":       3,
		"disabled":       4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_version_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_version_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{0}
}

type ApplyRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Product                 string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	OperatorVersion         string                 `protobuf:"bytes,2,opt,name=operator_version,json=operatorVersion,proto3" json:"operator_version,omitempty"`
	Apply                   string                 `protobuf:"bytes,3,opt,name=apply,proto3" json:"apply,omitempty"`
	DatabaseVersion         string                 `protobuf:"bytes,4,opt,name=database_version,json=databaseVersion,proto3" json:"database_version,omitempty"`
	KubeVersion             string                 `protobuf:"bytes,5,opt,name=kube_version,json=kubeVersion,proto3" json:"kube_version,omitempty"`
	Platform                string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	PmmVersion              string                 `protobuf:"bytes,7,opt,name=pmm_version,json=pmmVersion,proto3" json:"pmm_version,omitempty"`
	BackupVersion           string                 `protobuf:"bytes,8,opt,name=backup_version,json=backupVersion,proto3" json:"backup_version,omitempty"`
	ProxysqlVersion         string                 `protobuf:"bytes,9,opt,name=proxysql_version,json=proxysqlVersion,proto3" json:"proxysql_version,omitempty"`
	HaproxyVersion          string                 `protobuf:"bytes,10,opt,name=haproxy_version,json=haproxyVersion,proto3" json:"haproxy_version,omitempty"`
	NamespaceUid            string                 `protobuf:"bytes,11,opt,name=namespace_uid,json=namespaceUid,proto3" json:"namespace_uid,omitempty"`
	CustomResourceUid       string                 `protobuf:"bytes,12,opt,name=custom_resource_uid,json=customResourceUid,proto3" json:"custom_resource_uid,omitempty"`
	LogCollectorVersion     string                 `protobuf:"bytes,13,opt,name=log_collector_version,json=logCollectorVersion,proto3" json:"log_collector_version,omitempty"`
	ShardingEnabled         bool                   `protobuf:"varint,14,opt,name=sharding_enabled,json=shardingEnabled,proto3" json:"sharding_enabled,omitempty"`
	HashicorpVaultEnabled   bool                   `protobuf:"varint,15,opt,name=hashicorp_vault_enabled,json=hashicorpVaultEnabled,proto3" json:"hashicorp_vault_enabled,omitempty"`
	ClusterWideEnabled      bool                   `protobuf:"varint,16,opt,name=cluster_wide_enabled,json=clusterWideEnabled,proto3" json:"cluster_wide_enabled,omitempty"`
	PmmEnabled              bool                   `protobuf:"varint,17,opt,name=pmm_enabled,json=pmmEnabled,proto3" json:"pmm_enabled,omitempty"`
	HelmDeployOperator      bool                   `protobuf:"varint,18,opt,name=helm_deploy_operator,json=helmDeployOperator,proto3" json:"helm_deploy_operator,omitempty"`
	HelmDeployCr            bool                   `protobuf:"varint,19,opt,name=helm_deploy_cr,json=helmDeployCr,proto3" json:"helm_deploy_cr,omitempty"`
	SidecarsUsed            bool                   `protobuf:"varint,20,opt,name=sidecars_used,json=sidecarsUsed,proto3" json:"sidecars_used,omitempty"`
	BackupsEnabled          bool                   `protobuf:"varint,21,opt,name=backups_enabled,json=backupsEnabled,proto3" json:"backups_enabled,omitempty"`
	ClusterSize             int32                  `protobuf:"varint,22,opt,name=cluster_size,json=clusterSize,proto3" json:"cluster_size,omitempty"`
	PitrEnabled             bool                   `protobuf:"varint,23,opt,name=pitr_enabled,json=pitrEnabled,proto3" json:"pitr_enabled,omitempty"`
	PhysicalBackupScheduled bool                   `protobuf:"varint,24,opt,name=physical_backup_scheduled,json=physicalBackupScheduled,proto3" json:"physical_backup_scheduled,omitempty"`
	Extensions              string                 `protobuf:"bytes,25,opt,name=extensions,proto3" json:"extensions,omitempty"`
	UserManagementEnabled   bool                   `protobuf:"varint,26,opt,name=user_management_enabled,json=userManagementEnabled,proto3" json:"user_management_enabled,omitempty"`
	RoleManagementEnabled   bool                   `protobuf:"varint,27,opt,name=role_management_enabled,json=roleManagementEnabled,proto3" json:"role_management_enabled,omitempty"`
	McsEnabled              bool                   `protobuf:"varint,28,opt,name=mcs_enabled,json=mcsEnabled,proto3" json:"mcs_enabled,omitempty"`
	VolumeExpansionEnabled  bool                   `protobuf:"varint,29,opt,name=volume_expansion_enabled,json=volumeExpansionEnabled,proto3" json:"volume_expansion_enabled,omitempty"`
	Distribution            string                 `protobuf:"bytes,30,opt,name=distribution,proto3" json:"distribution,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_api_version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *ApplyRequest) GetOperatorVersion() string {
	if x != nil {
		return x.OperatorVersion
	}
	return ""
}

func (x *ApplyRequest) GetApply() string {
	if x != nil {
		return x.Apply
	}
	return ""
}

func (x *ApplyRequest) GetDatabaseVersion() string {
	if x != nil {
		return x.DatabaseVersion
	}
	return ""
}

func (x *ApplyRequest) GetKubeVersion() string {
	if x != nil {
		return x.KubeVersion
	}
	return ""
}

func (x *ApplyRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ApplyRequest) GetPmmVersion() string {
	if x != nil {
		return x.PmmVersion
	}
	return ""
}

func (x *ApplyRequest) GetBackupVersion() string {
	if x != nil {
		return x.BackupVersion
	}
	return ""
}

func (x *ApplyRequest) GetProxysqlVersion() string {
	if x != nil {
		return x.ProxysqlVersion
	}
	return ""
}

func (x *ApplyRequest) GetHaproxyVersion() string {
	if x != nil {
		return x.HaproxyVersion
	}
	return ""
}

func (x *ApplyRequest) GetNamespaceUid() string {
	if x != nil {
		return x.NamespaceUid
	}
	return ""
}

func (x *ApplyRequest) GetCustomResourceUid() string {
	if x != nil {
		return x.CustomResourceUid
	}
	return ""
}

func (x *ApplyRequest) GetLogCollectorVersion() string {
	if x != nil {
		return x.LogCollectorVersion
	}
	return ""
}

func (x *ApplyRequest) GetShardingEnabled() bool {
	if x != nil {
		return x.ShardingEnabled
	}
	return false
}

func (x *ApplyRequest) GetHashicorpVaultEnabled() bool {
	if x != nil {
		return x.HashicorpVaultEnabled
	}
	return false
}

func (x *ApplyRequest) GetClusterWideEnabled() bool {
	if x != nil {
		return x.ClusterWideEnabled
	}
	return false
}

func (x *ApplyRequest) GetPmmEnabled() bool {
	if x != nil {
		return x.PmmEnabled
	}
	return false
}

func (x *ApplyRequest) GetHelmDeployOperator() bool {
	if x != nil {
		return x.HelmDeployOperator
	}
	return false
}

func (x *ApplyRequest) GetHelmDeployCr() bool {
	if x != nil {
		return x.HelmDeployCr
	}
	return false
}

func (x *ApplyRequest) GetSidecarsUsed() bool {
	if x != nil {
		return x.SidecarsUsed
	}
	return false
}

func (x *ApplyRequest) GetBackupsEnabled() bool {
	if x != nil {
		return x.BackupsEnabled
	}
	return false
}

func (x *ApplyRequest) GetClusterSize() int32 {
	if x != nil {
		return x.ClusterSize
	}
	return 0
}

func (x *ApplyRequest) GetPitrEnabled() bool {
	if x != nil {
		return x.PitrEnabled
	}
	return false
}

func (x *ApplyRequest) GetPhysicalBackupScheduled() bool {
	if x != nil {
		return x.PhysicalBackupScheduled
	}
	return false
}

func (x *ApplyRequest) GetExtensions() string {
	if x != nil {
		return x.Extensions
	}
	return ""
}

func (x *ApplyRequest) GetUserManagementEnabled() bool {
	if x != nil {
		return x.UserManagementEnabled
	}
	return false
}

func (x *ApplyRequest) GetRoleManagementEnabled() bool {
	if x != nil {
		return x.RoleManagementEnabled
	}
	return false
}

func (x *ApplyRequest) GetMcsEnabled() bool {
	if x != nil {
		return x.McsEnabled
	}
	return false
}

func (x *ApplyRequest) GetVolumeExpansionEnabled() bool {
	if x != nil {
		return x.VolumeExpansionEnabled
	}
	return false
}

func (x *ApplyRequest) GetDistribution() string {
	if x != nil {
		return x.Distribution
	}
	return ""
}

type OperatorRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Product                 string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	OperatorVersion         string                 `protobuf:"bytes,2,opt,name=operator_version,json=operatorVersion,proto3" json:"operator_version,omitempty"`
	DatabaseVersion         string                 `protobuf:"bytes,4,opt,name=database_version,json=databaseVersion,proto3" json:"database_version,omitempty"`
	KubeVersion             string                 `protobuf:"bytes,5,opt,name=kube_version,json=kubeVersion,proto3" json:"kube_version,omitempty"`
	Platform                string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	PmmVersion              string                 `protobuf:"bytes,7,opt,name=pmm_version,json=pmmVersion,proto3" json:"pmm_version,omitempty"`
	BackupVersion           string                 `protobuf:"bytes,8,opt,name=backup_version,json=backupVersion,proto3" json:"backup_version,omitempty"`
	ProxysqlVersion         string                 `protobuf:"bytes,9,opt,name=proxysql_version,json=proxysqlVersion,proto3" json:"proxysql_version,omitempty"`
	HaproxyVersion          string                 `protobuf:"bytes,10,opt,name=haproxy_version,json=haproxyVersion,proto3" json:"haproxy_version,omitempty"`
	NamespaceUid            string                 `protobuf:"bytes,11,opt,name=namespace_uid,json=namespaceUid,proto3" json:"namespace_uid,omitempty"`
	CustomResourceUid       string                 `protobuf:"bytes,12,opt,name=custom_resource_uid,json=customResourceUid,proto3" json:"custom_resource_uid,omitempty"`
	LogCollectorVersion     string                 `protobuf:"bytes,13,opt,name=log_collector_version,json=logCollectorVersion,proto3" json:"log_collector_version,omitempty"`
	ShardingEnabled         bool                   `protobuf:"varint,14,opt,name=sharding_enabled,json=shardingEnabled,proto3" json:"sharding_enabled,omitempty"`
	HashicorpVaultEnabled   bool                   `protobuf:"varint,15,opt,name=hashicorp_vault_enabled,json=hashicorpVaultEnabled,proto3" json:"hashicorp_vault_enabled,omitempty"`
	ClusterWideEnabled      bool                   `protobuf:"varint,16,opt,name=cluster_wide_enabled,json=clusterWideEnabled,proto3" json:"cluster_wide_enabled,omitempty"`
	PmmEnabled              bool                   `protobuf:"varint,17,opt,name=pmm_enabled,json=pmmEnabled,proto3" json:"pmm_enabled,omitempty"`
	HelmDeployOperator      bool                   `protobuf:"varint,18,opt,name=helm_deploy_operator,json=helmDeployOperator,proto3" json:"helm_deploy_operator,omitempty"`
	HelmDeployCr            bool                   `protobuf:"varint,19,opt,name=helm_deploy_cr,json=helmDeployCr,proto3" json:"helm_deploy_cr,omitempty"`
	SidecarsUsed            bool                   `protobuf:"varint,20,opt,name=sidecars_used,json=sidecarsUsed,proto3" json:"sidecars_used,omitempty"`
	BackupsEnabled          bool                   `protobuf:"varint,21,opt,name=backups_enabled,json=backupsEnabled,proto3" json:"backups_enabled,omitempty"`
	ClusterSize             int32                  `protobuf:"varint,22,opt,name=cluster_size,json=clusterSize,proto3" json:"cluster_size,omitempty"`
	PitrEnabled             bool                   `protobuf:"varint,23,opt,name=pitr_enabled,json=pitrEnabled,proto3" json:"pitr_enabled,omitempty"`
	PhysicalBackupScheduled bool                   `protobuf:"varint,24,opt,name=physical_backup_scheduled,json=physicalBackupScheduled,proto3" json:"physical_backup_scheduled,omitempty"`
	Extensions              string                 `protobuf:"bytes,25,opt,name=extensions,proto3" json:"extensions,omitempty"`
	UserManagementEnabled   bool                   `protobuf:"varint,26,opt,name=user_management_enabled,json=userManagementEnabled,proto3" json:"user_management_enabled,omitempty"`
	RoleManagementEnabled   bool                   `protobuf:"varint,27,opt,name=role_management_enabled,json=roleManagementEnabled,proto3" json:"role_management_enabled,omitempty"`
	McsEnabled              bool                   `protobuf:"varint,28,opt,name=mcs_enabled,json=mcsEnabled,proto3" json:"mcs_enabled,omitempty"`
	VolumeExpansionEnabled  bool                   `protobuf:"varint,29,opt,name=volume_expansion_enabled,json=volumeExpansionEnabled,proto3" json:"volume_expansion_enabled,omitempty"`
	Distribution            string                 `protobuf:"bytes,30,opt,name=distribution,proto3" json:"distribution,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OperatorRequest) Reset() {
	*x = OperatorRequest{}
	mi := &file_api_version_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorRequest) ProtoMessage() {}

func (x *OperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorRequest.ProtoReflect.Descriptor instead.
func (*OperatorRequest) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{1}
}

func (x *OperatorRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *OperatorRequest) GetOperatorVersion() string {
	if x != nil {
		return x.OperatorVersion
	}
	return ""
}

func (x *OperatorRequest) GetDatabaseVersion() string {
	if x != nil {
		return x.DatabaseVersion
	}
	return ""
}

func (x *OperatorRequest) GetKubeVersion() string {
	if x != nil {
		return x.KubeVersion
	}
	return ""
}

func (x *OperatorRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *OperatorRequest) GetPmmVersion() string {
	if x != nil {
		return x.PmmVersion
	}
	return ""
}

func (x *OperatorRequest) GetBackupVersion() string {
	if x != nil {
		return x.BackupVersion
	}
	return ""
}

func (x *OperatorRequest) GetProxysqlVersion() string {
	if x != nil {
		return x.ProxysqlVersion
	}
	return ""
}

func (x *OperatorRequest) GetHaproxyVersion() string {
	if x != nil {
		return x.HaproxyVersion
	}
	return ""
}

func (x *OperatorRequest) GetNamespaceUid() string {
	if x != nil {
		return x.NamespaceUid
	}
	return ""
}

func (x *OperatorRequest) GetCustomResourceUid() string {
	if x != nil {
		return x.CustomResourceUid
	}
	return ""
}

func (x *OperatorRequest) GetLogCollectorVersion() string {
	if x != nil {
		return x.LogCollectorVersion
	}
	return ""
}

func (x *OperatorRequest) GetShardingEnabled() bool {
	if x != nil {
		return x.ShardingEnabled
	}
	return false
}

func (x *OperatorRequest) GetHashicorpVaultEnabled() bool {
	if x != nil {
		return x.HashicorpVaultEnabled
	}
	return false
}

func (x *OperatorRequest) GetClusterWideEnabled() bool {
	if x != nil {
		return x.ClusterWideEnabled
	}
	return false
}

func (x *OperatorRequest) GetPmmEnabled() bool {
	if x != nil {
		return x.PmmEnabled
	}
	return false
}

func (x *OperatorRequest) GetHelmDeployOperator() bool {
	if x != nil {
		return x.HelmDeployOperator
	}
	return false
}

func (x *OperatorRequest) GetHelmDeployCr() bool {
	if x != nil {
		return x.HelmDeployCr
	}
	return false
}

func (x *OperatorRequest) GetSidecarsUsed() bool {
	if x != nil {
		return x.SidecarsUsed
	}
	return false
}

func (x *OperatorRequest) GetBackupsEnabled() bool {
	if x != nil {
		return x.BackupsEnabled
	}
	return false
}

func (x *OperatorRequest) GetClusterSize() int32 {
	if x != nil {
		return x.ClusterSize
	}
	return 0
}

func (x *OperatorRequest) GetPitrEnabled() bool {
	if x != nil {
		return x.PitrEnabled
	}
	return false
}

func (x *OperatorRequest) GetPhysicalBackupScheduled() bool {
	if x != nil {
		return x.PhysicalBackupScheduled
	}
	return false
}

func (x *OperatorRequest) GetExtensions() string {
	if x != nil {
		return x.Extensions
	}
	return ""
}

func (x *OperatorRequest) GetUserManagementEnabled() bool {
	if x != nil {
		return x.UserManagementEnabled
	}
	return false
}

func (x *OperatorRequest) GetRoleManagementEnabled() bool {
	if x != nil {
		return x.RoleManagementEnabled
	}
	return false
}

func (x *OperatorRequest) GetMcsEnabled() bool {
	if x != nil {
		return x.McsEnabled
	}
	return false
}

func (x *OperatorRequest) GetVolumeExpansionEnabled() bool {
	if x != nil {
		return x.VolumeExpansionEnabled
	}
	return false
}

func (x *OperatorRequest) GetDistribution() string {
	if x != nil {
		return x.Distribution
	}
	return ""
}

type ProductRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Product                 string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	DatabaseVersion         string                 `protobuf:"bytes,4,opt,name=database_version,json=databaseVersion,proto3" json:"database_version,omitempty"`
	KubeVersion             string                 `protobuf:"bytes,5,opt,name=kube_version,json=kubeVersion,proto3" json:"kube_version,omitempty"`
	Platform                string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	PmmVersion              string                 `protobuf:"bytes,7,opt,name=pmm_version,json=pmmVersion,proto3" json:"pmm_version,omitempty"`
	BackupVersion           string                 `protobuf:"bytes,8,opt,name=backup_version,json=backupVersion,proto3" json:"backup_version,omitempty"`
	ProxysqlVersion         string                 `protobuf:"bytes,9,opt,name=proxysql_version,json=proxysqlVersion,proto3" json:"proxysql_version,omitempty"`
	HaproxyVersion          string                 `protobuf:"bytes,10,opt,name=haproxy_version,json=haproxyVersion,proto3" json:"haproxy_version,omitempty"`
	NamespaceUid            string                 `protobuf:"bytes,11,opt,name=namespace_uid,json=namespaceUid,proto3" json:"namespace_uid,omitempty"`
	CustomResourceUid       string                 `protobuf:"bytes,12,opt,name=custom_resource_uid,json=customResourceUid,proto3" json:"custom_resource_uid,omitempty"`
	LogCollectorVersion     string                 `protobuf:"bytes,13,opt,name=log_collector_version,json=logCollectorVersion,proto3" json:"log_collector_version,omitempty"`
	ShardingEnabled         bool                   `protobuf:"varint,14,opt,name=sharding_enabled,json=shardingEnabled,proto3" json:"sharding_enabled,omitempty"`
	HashicorpVaultEnabled   bool                   `protobuf:"varint,15,opt,name=hashicorp_vault_enabled,json=hashicorpVaultEnabled,proto3" json:"hashicorp_vault_enabled,omitempty"`
	ClusterWideEnabled      bool                   `protobuf:"varint,16,opt,name=cluster_wide_enabled,json=clusterWideEnabled,proto3" json:"cluster_wide_enabled,omitempty"`
	PmmEnabled              bool                   `protobuf:"varint,17,opt,name=pmm_enabled,json=pmmEnabled,proto3" json:"pmm_enabled,omitempty"`
	HelmDeployOperator      bool                   `protobuf:"varint,18,opt,name=helm_deploy_operator,json=helmDeployOperator,proto3" json:"helm_deploy_operator,omitempty"`
	HelmDeployCr            bool                   `protobuf:"varint,19,opt,name=helm_deploy_cr,json=helmDeployCr,proto3" json:"helm_deploy_cr,omitempty"`
	SidecarsUsed            bool                   `protobuf:"varint,20,opt,name=sidecars_used,json=sidecarsUsed,proto3" json:"sidecars_used,omitempty"`
	BackupsEnabled          bool                   `protobuf:"varint,21,opt,name=backups_enabled,json=backupsEnabled,proto3" json:"backups_enabled,omitempty"`
	ClusterSize             int32                  `protobuf:"varint,22,opt,name=cluster_size,json=clusterSize,proto3" json:"cluster_size,omitempty"`
	PitrEnabled             bool                   `protobuf:"varint,23,opt,name=pitr_enabled,json=pitrEnabled,proto3" json:"pitr_enabled,omitempty"`
	PhysicalBackupScheduled bool                   `protobuf:"varint,24,opt,name=physical_backup_scheduled,json=physicalBackupScheduled,proto3" json:"physical_backup_scheduled,omitempty"`
	Extensions              string                 `protobuf:"bytes,25,opt,name=extensions,proto3" json:"extensions,omitempty"`
	UserManagementEnabled   bool                   `protobuf:"varint,26,opt,name=user_management_enabled,json=userManagementEnabled,proto3" json:"user_management_enabled,omitempty"`
	RoleManagementEnabled   bool                   `protobuf:"varint,27,opt,name=role_management_enabled,json=roleManagementEnabled,proto3" json:"role_management_enabled,omitempty"`
	McsEnabled              bool                   `protobuf:"varint,28,opt,name=mcs_enabled,json=mcsEnabled,proto3" json:"mcs_enabled,omitempty"`
	VolumeExpansionEnabled  bool                   `protobuf:"varint,29,opt,name=volume_expansion_enabled,json=volumeExpansionEnabled,proto3" json:"volume_expansion_enabled,omitempty"`
	Distribution            string                 `protobuf:"bytes,30,opt,name=distribution,proto3" json:"distribution,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_api_version_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{2}
}

func (x *ProductRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *ProductRequest) GetDatabaseVersion() string {
	if x != nil {
		return x.DatabaseVersion
	}
	return ""
}

func (x *ProductRequest) GetKubeVersion() string {
	if x != nil {
		return x.KubeVersion
	}
	return ""
}

func (x *ProductRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ProductRequest) GetPmmVersion() string {
	if x != nil {
		return x.PmmVersion
	}
	return ""
}

func (x *ProductRequest) GetBackupVersion() string {
	if x != nil {
		return x.BackupVersion
	}
	return ""
}

func (x *ProductRequest) GetProxysqlVersion() string {
	if x != nil {
		return x.ProxysqlVersion
	}
	return ""
}

func (x *ProductRequest) GetHaproxyVersion() string {
	if x != nil {
		return x.HaproxyVersion
	}
	return ""
}

func (x *ProductRequest) GetNamespaceUid() string {
	if x != nil {
		return x.NamespaceUid
	}
	return ""
}

func (x *ProductRequest) GetCustomResourceUid() string {
	if x != nil {
		return x.CustomResourceUid
	}
	return ""
}

func (x *ProductRequest) GetLogCollectorVersion() string {
	if x != nil {
		return x.LogCollectorVersion
	}
	return ""
}

func (x *ProductRequest) GetShardingEnabled() bool {
	if x != nil {
		return x.ShardingEnabled
	}
	return false
}

func (x *ProductRequest) GetHashicorpVaultEnabled() bool {
	if x != nil {
		return x.HashicorpVaultEnabled
	}
	return false
}

func (x *ProductRequest) GetClusterWideEnabled() bool {
	if x != nil {
		return x.ClusterWideEnabled
	}
	return false
}

func (x *ProductRequest) GetPmmEnabled() bool {
	if x != nil {
		return x.PmmEnabled
	}
	return false
}

func (x *ProductRequest) GetHelmDeployOperator() bool {
	if x != nil {
		return x.HelmDeployOperator
	}
	return false
}

func (x *ProductRequest) GetHelmDeployCr() bool {
	if x != nil {
		return x.HelmDeployCr
	}
	return false
}

func (x *ProductRequest) GetSidecarsUsed() bool {
	if x != nil {
		return x.SidecarsUsed
	}
	return false
}

func (x *ProductRequest) GetBackupsEnabled() bool {
	if x != nil {
		return x.BackupsEnabled
	}
	return false
}

func (x *ProductRequest) GetClusterSize() int32 {
	if x != nil {
		return x.ClusterSize
	}
	return 0
}

func (x *ProductRequest) GetPitrEnabled() bool {
	if x != nil {
		return x.PitrEnabled
	}
	return false
}

func (x *ProductRequest) GetPhysicalBackupScheduled() bool {
	if x != nil {
		return x.PhysicalBackupScheduled
	}
	return false
}

func (x *ProductRequest) GetExtensions() string {
	if x != nil {
		return x.Extensions
	}
	return ""
}

func (x *ProductRequest) GetUserManagementEnabled() bool {
	if x != nil {
		return x.UserManagementEnabled
	}
	return false
}

func (x *ProductRequest) GetRoleManagementEnabled() bool {
	if x != nil {
		return x.RoleManagementEnabled
	}
	return false
}

func (x *ProductRequest) GetMcsEnabled() bool {
	if x != nil {
		return x.McsEnabled
	}
	return false
}

func (x *ProductRequest) GetVolumeExpansionEnabled() bool {
	if x != nil {
		return x.VolumeExpansionEnabled
	}
	return false
}

func (x *ProductRequest) GetDistribution() string {
	if x != nil {
		return x.Distribution
	}
	return ""
}

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_api_version_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{3}
}

func (x *MetadataRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

// Version represents product version information.
type Version struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImagePath      string                 `protobuf:"bytes,1,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	ImageHash      string                 `protobuf:"bytes,2,opt,name=image_hash,json=imageHash,proto3" json:"image_hash,omitempty"`
	ImageHashArm64 string                 `protobuf:"bytes,3,opt,name=image_hash_arm64,json=imageHashArm64,proto3" json:"image_hash_arm64,omitempty"`
	Status         Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=version.Status" json:"status,omitempty"`
	Critical       bool                   `protobuf:"varint,5,opt,name=critical,proto3" json:"critical,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_api_version_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{4}
}

func (x *Version) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *Version) GetImageHash() string {
	if x != nil {
		return x.ImageHash
	}
	return ""
}

func (x *Version) GetImageHashArm64() string {
	if x != nil {
		return x.ImageHashArm64
	}
	return ""
}

func (x *Version) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_status_invalid
}

func (x *Version) GetCritical() bool {
	if x != nil {
		return x.Critical
	}
	return false
}

// Version represents product version information.
type VersionV2 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImagePath      string                 `protobuf:"bytes,1,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	ImageHash      string                 `protobuf:"bytes,2,opt,name=image_hash,json=imageHash,proto3" json:"image_hash,omitempty"`
	ImageHashArm64 string                 `protobuf:"bytes,3,opt,name=image_hash_arm64,json=imageHashArm64,proto3" json:"image_hash_arm64,omitempty"`
	// release_timestamp is the release time of this image.
	ImageReleaseTimestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=image_release_timestamp,json=imageReleaseTimestamp,proto3" json:"image_release_timestamp,omitempty"`
	Status                Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=version.Status" json:"status,omitempty"`
	Critical              bool                   `protobuf:"varint,5,opt,name=critical,proto3" json:"critical,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VersionV2) Reset() {
	*x = VersionV2{}
	mi := &file_api_version_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionV2) ProtoMessage() {}

func (x *VersionV2) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionV2.ProtoReflect.Descriptor instead.
func (*VersionV2) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{5}
}

func (x *VersionV2) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *VersionV2) GetImageHash() string {
	if x != nil {
		return x.ImageHash
	}
	return ""
}

func (x *VersionV2) GetImageHashArm64() string {
	if x != nil {
		return x.ImageHashArm64
	}
	return ""
}

func (x *VersionV2) GetImageReleaseTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ImageReleaseTimestamp
	}
	return nil
}

func (x *VersionV2) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_status_invalid
}

func (x *VersionV2) GetCritical() bool {
	if x != nil {
		return x.Critical
	}
	return false
}

// VersionMatrix represents set of possible product versions.
type VersionMatrix struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Mongod              map[string]*Version    `protobuf:"bytes,1,rep,name=mongod,proto3" json:"mongod,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Pxc                 map[string]*Version    `protobuf:"bytes,2,rep,name=pxc,proto3" json:"pxc,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Pmm                 map[string]*Version    `protobuf:"bytes,3,rep,name=pmm,proto3" json:"pmm,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Proxysql            map[string]*Version    `protobuf:"bytes,4,rep,name=proxysql,proto3" json:"proxysql,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Haproxy             map[string]*Version    `protobuf:"bytes,5,rep,name=haproxy,proto3" json:"haproxy,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Backup              map[string]*Version    `protobuf:"bytes,6,rep,name=backup,proto3" json:"backup,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Operator            map[string]*Version    `protobuf:"bytes,7,rep,name=operator,proto3" json:"operator,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LogCollector        map[string]*Version    `protobuf:"bytes,8,rep,name=log_collector,json=logCollector,proto3" json:"log_collector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Postgresql          map[string]*Version    `protobuf:"bytes,9,rep,name=postgresql,proto3" json:"postgresql,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Pgbackrest          map[string]*Version    `protobuf:"bytes,10,rep,name=pgbackrest,proto3" json:"pgbackrest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PgbackrestRepo      map[string]*Version    `protobuf:"bytes,11,rep,name=pgbackrest_repo,json=pgbackrestRepo,proto3" json:"pgbackrest_repo,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Pgbadger            map[string]*Version    `protobuf:"bytes,12,rep,name=pgbadger,proto3" json:"pgbadger,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Pgbouncer           map[string]*Version    `protobuf:"bytes,13,rep,name=pgbouncer,proto3" json:"pgbouncer,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PxcOperator         map[string]*Version    `protobuf:"bytes,14,rep,name=pxc_operator,json=pxcOperator,proto3" json:"pxc_operator,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PsmdbOperator       map[string]*Version    `protobuf:"bytes,15,rep,name=psmdb_operator,json=psmdbOperator,proto3" json:"psmdb_operator,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PgOperatorApiserver map[string]*Version    `protobuf:"bytes,16,rep,name=pg_operator_apiserver,json=pgOperatorApiserver,proto3" json:"pg_operator_apiserver,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PgOperatorEvent     map[string]*Version    `protobuf:"bytes,17,rep,name=pg_operator_event,json=pgOperatorEvent,proto3" json:"pg_operator_event,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PgOperatorRmdata    map[string]*Version    `protobuf:"bytes,18,rep,name=pg_operator_rmdata,json=pgOperatorRmdata,proto3" json:"pg_operator_rmdata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PgOperatorScheduler map[string]*Version    `protobuf:"bytes,19,rep,name=pg_operator_scheduler,json=pgOperatorScheduler,proto3" json:"pg_operator_scheduler,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PgOperator          map[string]*Version    `protobuf:"bytes,20,rep,name=pg_operator,json=pgOperator,proto3" json:"pg_operator,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PgOperatorDeployer  map[string]*Version    `protobuf:"bytes,21,rep,name=pg_operator_deployer,json=pgOperatorDeployer,proto3" json:"pg_operator_deployer,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PsOperator          map[string]*Version    `protobuf:"bytes,22,rep,name=ps_operator,json=psOperator,proto3" json:"ps_operator,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Mysql               map[string]*Version    `protobuf:"bytes,23,rep,name=mysql,proto3" json:"mysql,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Router              map[string]*Version    `protobuf:"bytes,24,rep,name=router,proto3" json:"router,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Orchestrator        map[string]*Version    `protobuf:"bytes,25,rep,name=orchestrator,proto3" json:"orchestrator,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Toolkit             map[string]*Version    `protobuf:"bytes,26,rep,name=toolkit,proto3" json:"toolkit,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Postgis             map[string]*Version    `protobuf:"bytes,27,rep,name=postgis,proto3" json:"postgis,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BinlogServer        map[string]*Version    `protobuf:"bytes,28,rep,name=binlog_server,json=binlogServer,proto3" json:"binlog_server,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Pgupgrade           map[string]*Version    `protobuf:"bytes,29,rep,name=pgupgrade,proto3" json:"pgupgrade,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VersionMatrix) Reset() {
	*x = VersionMatrix{}
	mi := &file_api_version_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionMatrix) ProtoMessage() {}

func (x *VersionMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionMatrix.ProtoReflect.Descriptor instead.
func (*VersionMatrix) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{6}
}

func (x *VersionMatrix) GetMongod() map[string]*Version {
	if x != nil {
		return x.Mongod
	}
	return nil
}

func (x *VersionMatrix) GetPxc() map[string]*Version {
	if x != nil {
		return x.Pxc
	}
	return nil
}

func (x *VersionMatrix) GetPmm() map[string]*Version {
	if x != nil {
		return x.Pmm
	}
	return nil
}

func (x *VersionMatrix) GetProxysql() map[string]*Version {
	if x != nil {
		return x.Proxysql
	}
	return nil
}

func (x *VersionMatrix) GetHaproxy() map[string]*Version {
	if x != nil {
		return x.Haproxy
	}
	return nil
}

func (x *VersionMatrix) GetBackup() map[string]*Version {
	if x != nil {
		return x.Backup
	}
	return nil
}

func (x *VersionMatrix) GetOperator() map[string]*Version {
	if x != nil {
		return x.Operator
	}
	return nil
}

func (x *VersionMatrix) GetLogCollector() map[string]*Version {
	if x != nil {
		return x.LogCollector
	}
	return nil
}

func (x *VersionMatrix) GetPostgresql() map[string]*Version {
	if x != nil {
		return x.Postgresql
	}
	return nil
}

func (x *VersionMatrix) GetPgbackrest() map[string]*Version {
	if x != nil {
		return x.Pgbackrest
	}
	return nil
}

func (x *VersionMatrix) GetPgbackrestRepo() map[string]*Version {
	if x != nil {
		return x.PgbackrestRepo
	}
	return nil
}

func (x *VersionMatrix) GetPgbadger() map[string]*Version {
	if x != nil {
		return x.Pgbadger
	}
	return nil
}

func (x *VersionMatrix) GetPgbouncer() map[string]*Version {
	if x != nil {
		return x.Pgbouncer
	}
	return nil
}

func (x *VersionMatrix) GetPxcOperator() map[string]*Version {
	if x != nil {
		return x.PxcOperator
	}
	return nil
}

func (x *VersionMatrix) GetPsmdbOperator() map[string]*Version {
	if x != nil {
		return x.PsmdbOperator
	}
	return nil
}

func (x *VersionMatrix) GetPgOperatorApiserver() map[string]*Version {
	if x != nil {
		return x.PgOperatorApiserver
	}
	return nil
}

func (x *VersionMatrix) GetPgOperatorEvent() map[string]*Version {
	if x != nil {
		return x.PgOperatorEvent
	}
	return nil
}

func (x *VersionMatrix) GetPgOperatorRmdata() map[string]*Version {
	if x != nil {
		return x.PgOperatorRmdata
	}
	return nil
}

func (x *VersionMatrix) GetPgOperatorScheduler() map[string]*Version {
	if x != nil {
		return x.PgOperatorScheduler
	}
	return nil
}

func (x *VersionMatrix) GetPgOperator() map[string]*Version {
	if x != nil {
		return x.PgOperator
	}
	return nil
}

func (x *VersionMatrix) GetPgOperatorDeployer() map[string]*Version {
	if x != nil {
		return x.PgOperatorDeployer
	}
	return nil
}

func (x *VersionMatrix) GetPsOperator() map[string]*Version {
	if x != nil {
		return x.PsOperator
	}
	return nil
}

func (x *VersionMatrix) GetMysql() map[string]*Version {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *VersionMatrix) GetRouter() map[string]*Version {
	if x != nil {
		return x.Router
	}
	return nil
}

func (x *VersionMatrix) GetOrchestrator() map[string]*Version {
	if x != nil {
		return x.Orchestrator
	}
	return nil
}

func (x *VersionMatrix) GetToolkit() map[string]*Version {
	if x != nil {
		return x.Toolkit
	}
	return nil
}

func (x *VersionMatrix) GetPostgis() map[string]*Version {
	if x != nil {
		return x.Postgis
	}
	return nil
}

func (x *VersionMatrix) GetBinlogServer() map[string]*Version {
	if x != nil {
		return x.BinlogServer
	}
	return nil
}

func (x *VersionMatrix) GetPgupgrade() map[string]*Version {
	if x != nil {
		return x.Pgupgrade
	}
	return nil
}

// OperatorVersion represents operator version.
type OperatorVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Matrix        *VersionMatrix         `protobuf:"bytes,3,opt,name=matrix,proto3" json:"matrix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorVersion) Reset() {
	*x = OperatorVersion{}
	mi := &file_api_version_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorVersion) ProtoMessage() {}

func (x *OperatorVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorVersion.ProtoReflect.Descriptor instead.
func (*OperatorVersion) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{7}
}

func (x *OperatorVersion) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *OperatorVersion) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *OperatorVersion) GetMatrix() *VersionMatrix {
	if x != nil {
		return x.Matrix
	}
	return nil
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*OperatorVersion     `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_api_version_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{8}
}

func (x *VersionResponse) GetVersions() []*OperatorVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type OperatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*OperatorVersion     `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorResponse) Reset() {
	*x = OperatorResponse{}
	mi := &file_api_version_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorResponse) ProtoMessage() {}

func (x *OperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorResponse.ProtoReflect.Descriptor instead.
func (*OperatorResponse) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{9}
}

func (x *OperatorResponse) GetVersions() []*OperatorVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*OperatorVersion     `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_api_version_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{10}
}

func (x *ProductResponse) GetVersions() []*OperatorVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

// MetadataVersion represents metadata for a given version.
type MetadataVersion struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Recommended is the recommended version for a given component.
	Recommended map[string]string `protobuf:"bytes,2,rep,name=recommended,proto3" json:"recommended,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Supported holds semver constraint per component, such as ">= 1.0, < 1.4".
	Supported     map[string]string `protobuf:"bytes,3,rep,name=supported,proto3" json:"supported,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataVersion) Reset() {
	*x = MetadataVersion{}
	mi := &file_api_version_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataVersion) ProtoMessage() {}

func (x *MetadataVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataVersion.ProtoReflect.Descriptor instead.
func (*MetadataVersion) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{11}
}

func (x *MetadataVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetadataVersion) GetRecommended() map[string]string {
	if x != nil {
		return x.Recommended
	}
	return nil
}

func (x *MetadataVersion) GetSupported() map[string]string {
	if x != nil {
		return x.Supported
	}
	return nil
}

// MetadataV2Version represents metadata for a given version with additional fields.
type MetadataV2Version struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Recommended is the recommended version for a given component.
	Recommended map[string]string `protobuf:"bytes,2,rep,name=recommended,proto3" json:"recommended,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Supported holds semver constraint per component, such as ">= 1.0, < 1.4".
	Supported map[string]string `protobuf:"bytes,3,rep,name=supported,proto3" json:"supported,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ImageInfo holds information about the docker image for this version.
	ImageInfo     *VersionV2 `protobuf:"bytes,4,opt,name=image_info,json=imageInfo,proto3" json:"image_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataV2Version) Reset() {
	*x = MetadataV2Version{}
	mi := &file_api_version_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataV2Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataV2Version) ProtoMessage() {}

func (x *MetadataV2Version) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataV2Version.ProtoReflect.Descriptor instead.
func (*MetadataV2Version) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{12}
}

func (x *MetadataV2Version) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetadataV2Version) GetRecommended() map[string]string {
	if x != nil {
		return x.Recommended
	}
	return nil
}

func (x *MetadataV2Version) GetSupported() map[string]string {
	if x != nil {
		return x.Supported
	}
	return nil
}

func (x *MetadataV2Version) GetImageInfo() *VersionV2 {
	if x != nil {
		return x.ImageInfo
	}
	return nil
}

type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*MetadataVersion     `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_api_version_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{13}
}

func (x *MetadataResponse) GetVersions() []*MetadataVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type MetadataV2Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*MetadataV2Version   `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataV2Response) Reset() {
	*x = MetadataV2Response{}
	mi := &file_api_version_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataV2Response) ProtoMessage() {}

func (x *MetadataV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataV2Response.ProtoReflect.Descriptor instead.
func (*MetadataV2Response) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{14}
}

func (x *MetadataV2Response) GetVersions() []*MetadataV2Version {
	if x != nil {
		return x.Versions
	}
	return nil
}

type GetReleaseNotesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Product name.
	Product string `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	// Product version.
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReleaseNotesRequest) Reset() {
	*x = GetReleaseNotesRequest{}
	mi := &file_api_version_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReleaseNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleaseNotesRequest) ProtoMessage() {}

func (x *GetReleaseNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleaseNotesRequest.ProtoReflect.Descriptor instead.
func (*GetReleaseNotesRequest) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{15}
}

func (x *GetReleaseNotesRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *GetReleaseNotesRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetReleaseNotesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The product name.
	Product string `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// release_notes is the release note for this version.
	ReleaseNote   string `protobuf:"bytes,3,opt,name=release_note,json=releaseNote,proto3" json:"release_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReleaseNotesResponse) Reset() {
	*x = GetReleaseNotesResponse{}
	mi := &file_api_version_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReleaseNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleaseNotesResponse) ProtoMessage() {}

func (x *GetReleaseNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_version_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleaseNotesResponse.ProtoReflect.Descriptor instead.
func (*GetReleaseNotesResponse) Descriptor() ([]byte, []int) {
	return file_api_version_proto_rawDescGZIP(), []int{16}
}

func (x *GetReleaseNotesResponse) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *GetReleaseNotesResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetReleaseNotesResponse) GetReleaseNote() string {
	if x != nil {
		return x.ReleaseNote
	}
	return ""
}

var File_api_version_proto protoreflect.FileDescriptor

const file_api_version_proto_rawDesc = "" +
	"\n" +
	"\x11api/version.proto\x12\aversion\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\n" +
	"\n" +
	"\fApplyRequest\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12)\n" +
	"\x10operator_version\x18\x02 \x01(\tR\x0foperatorVersion\x12\x14\n" +
	"\x05apply\x18\x03 \x01(\tR\x05apply\x12)\n" +
	"\x10database_version\x18\x04 \x01(\tR\x0fdatabaseVersion\x12!\n" +
	"\fkube_version\x18\x05 \x01(\tR\vkubeVersion\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12\x1f\n" +
	"\vpmm_version\x18\a \x01(\tR\n" +
	"pmmVersion\x12%\n" +
	"\x0ebackup_version\x18\b \x01(\tR\rbackupVersion\x12)\n" +
	"\x10proxysql_version\x18\t \x01(\tR\x0fproxysqlVersion\x12'\n" +
	"\x0fhaproxy_version\x18\n" +
	" \x01(\tR\x0ehaproxyVersion\x12#\n" +
	"\rnamespace_uid\x18\v \x01(\tR\fnamespaceUid\x12.\n" +
	"\x13custom_resource_uid\x18\f \x01(\tR\x11customResourceUid\x122\n" +
	"\x15log_collector_version\x18\r \x01(\tR\x13logCollectorVersion\x12)\n" +
	"\x10sharding_enabled\x18\x0e \x01(\bR\x0fshardingEnabled\x126\n" +
	"\x17hashicorp_vault_enabled\x18\x0f \x01(\bR\x15hashicorpVaultEnabled\x120\n" +
	"\x14cluster_wide_enabled\x18\x10 \x01(\bR\x12clusterWideEnabled\x12\x1f\n" +
	"\vpmm_enabled\x18\x11 \x01(\bR\n" +
	"pmmEnabled\x120\n" +
	"\x14helm_deploy_operator\x18\x12 \x01(\bR\x12helmDeployOperator\x12$\n" +
	"\x0ehelm_deploy_cr\x18\x13 \x01(\bR\fhelmDeployCr\x12#\n" +
	"\rsidecars_used\x18\x14 \x01(\bR\fsidecarsUsed\x12'\n" +
	"\x0fbackups_enabled\x18\x15 \x01(\bR\x0ebackupsEnabled\x12!\n" +
	"\fcluster_size\x18\x16 \x01(\x05R\vclusterSize\x12!\n" +
	"\fpitr_enabled\x18\x17 \x01(\bR\vpitrEnabled\x12:\n" +
	"\x19physical_backup_scheduled\x18\x18 \x01(\bR\x17physicalBackupScheduled\x12\x1e\n" +
	"\n" +
	"extensions\x18\x19 \x01(\tR\n" +
	"extensions\x126\n" +
	"\x17user_management_enabled\x18\x1a \x01(\bR\x15userManagementEnabled\x126\n" +
	"\x17role_management_enabled\x18\x1b \x01(\bR\x15roleManagementEnabled\x12\x1f\n" +
	"\vmcs_enabled\x18\x1c \x01(\bR\n" +
	"mcsEnabled\x128\n" +
	"\x18volume_expansion_enabled\x18\x1d \x01(\bR\x16volumeExpansionEnabled\x12\xaa\x01\n" +
	"\fdistribution\x18\x1e \x01(\tB\x85\x01\x92A\x81\x012fPostgreSQL distribution running in the cluster. Empty string means unknown (e.g. no running pods yet).\xf2\x02\x00\xf2\x02\apercona\xf2\x02\tcommunityR\fdistribution\"\xdb\n" +
	"\n" +
	"\x0fOperatorRequest\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12)\n" +
	"\x10operator_version\x18\x02 \x01(\tR\x0foperatorVersion\x12)\n" +
	"\x10database_version\x18\x04 \x01(\tR\x0fdatabaseVersion\x12!\n" +
	"\fkube_version\x18\x05 \x01(\tR\vkubeVersion\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12\x1f\n" +
	"\vpmm_version\x18\a \x01(\tR\n" +
	"pmmVersion\x12%\n" +
	"\x0ebackup_version\x18\b \x01(\tR\rbackupVersion\x12)\n" +
	"\x10proxysql_version\x18\t \x01(\tR\x0fproxysqlVersion\x12'\n" +
	"\x0fhaproxy_version\x18\n" +
	" \x01(\tR\x0ehaproxyVersion\x12#\n" +
	"\rnamespace_uid\x18\v \x01(\tR\fnamespaceUid\x12.\n" +
	"\x13custom_resource_uid\x18\f \x01(\tR\x11customResourceUid\x122\n" +
	"\x15log_collector_version\x18\r \x01(\tR\x13logCollectorVersion\x12)\n" +
	"\x10sharding_enabled\x18\x0e \x01(\bR\x0fshardingEnabled\x126\n" +
	"\x17hashicorp_vault_enabled\x18\x0f \x01(\bR\x15hashicorpVaultEnabled\x120\n" +
	"\x14cluster_wide_enabled\x18\x10 \x01(\bR\x12clusterWideEnabled\x12\x1f\n" +
	"\vpmm_enabled\x18\x11 \x01(\bR\n" +
	"pmmEnabled\x120\n" +
	"\x14helm_deploy_operator\x18\x12 \x01(\bR\x12helmDeployOperator\x12$\n" +
	"\x0ehelm_deploy_cr\x18\x13 \x01(\bR\fhelmDeployCr\x12#\n" +
	"\rsidecars_used\x18\x14 \x01(\bR\fsidecarsUsed\x12'\n" +
	"\x0fbackups_enabled\x18\x15 \x01(\bR\x0ebackupsEnabled\x12!\n" +
	"\fcluster_size\x18\x16 \x01(\x05R\vclusterSize\x12!\n" +
	"\fpitr_enabled\x18\x17 \x01(\bR\vpitrEnabled\x12:\n" +
	"\x19physical_backup_scheduled\x18\x18 \x01(\bR\x17physicalBackupScheduled\x12\x1e\n" +
	"\n" +
	"extensions\x18\x19 \x01(\tR\n" +
	"extensions\x126\n" +
	"\x17user_management_enabled\x18\x1a \x01(\bR\x15userManagementEnabled\x126\n" +
	"\x17role_management_enabled\x18\x1b \x01(\bR\x15roleManagementEnabled\x12\x1f\n" +
	"\vmcs_enabled\x18\x1c \x01(\bR\n" +
	"mcsEnabled\x128\n" +
	"\x18volume_expansion_enabled\x18\x1d \x01(\bR\x16volumeExpansionEnabled\x12\xaa\x01\n" +
	"\fdistribution\x18\x1e \x01(\tB\x85\x01\x92A\x81\x012fPostgreSQL distribution running in the cluster. Empty string means unknown (e.g. no running pods yet).\xf2\x02\x00\xf2\x02\apercona\xf2\x02\tcommunityR\fdistribution\"\xaf\n" +
	"\n" +
	"\x0eProductRequest\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12)\n" +
	"\x10database_version\x18\x04 \x01(\tR\x0fdatabaseVersion\x12!\n" +
	"\fkube_version\x18\x05 \x01(\tR\vkubeVersion\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12\x1f\n" +
	"\vpmm_version\x18\a \x01(\tR\n" +
	"pmmVersion\x12%\n" +
	"\x0ebackup_version\x18\b \x01(\tR\rbackupVersion\x12)\n" +
	"\x10proxysql_version\x18\t \x01(\tR\x0fproxysqlVersion\x12'\n" +
	"\x0fhaproxy_version\x18\n" +
	" \x01(\tR\x0ehaproxyVersion\x12#\n" +
	"\rnamespace_uid\x18\v \x01(\tR\fnamespaceUid\x12.\n" +
	"\x13custom_resource_uid\x18\f \x01(\tR\x11customResourceUid\x122\n" +
	"\x15log_collector_version\x18\r \x01(\tR\x13logCollectorVersion\x12)\n" +
	"\x10sharding_enabled\x18\x0e \x01(\bR\x0fshardingEnabled\x126\n" +
	"\x17hashicorp_vault_enabled\x18\x0f \x01(\bR\x15hashicorpVaultEnabled\x120\n" +
	"\x14cluster_wide_enabled\x18\x10 \x01(\bR\x12clusterWideEnabled\x12\x1f\n" +
	"\vpmm_enabled\x18\x11 \x01(\bR\n" +
	"pmmEnabled\x120\n" +
	"\x14helm_deploy_operator\x18\x12 \x01(\bR\x12helmDeployOperator\x12$\n" +
	"\x0ehelm_deploy_cr\x18\x13 \x01(\bR\fhelmDeployCr\x12#\n" +
	"\rsidecars_used\x18\x14 \x01(\bR\fsidecarsUsed\x12'\n" +
	"\x0fbackups_enabled\x18\x15 \x01(\bR\x0ebackupsEnabled\x12!\n" +
	"\fcluster_size\x18\x16 \x01(\x05R\vclusterSize\x12!\n" +
	"\fpitr_enabled\x18\x17 \x01(\bR\vpitrEnabled\x12:\n" +
	"\x19physical_backup_scheduled\x18\x18 \x01(\bR\x17physicalBackupScheduled\x12\x1e\n" +
	"\n" +
	"extensions\x18\x19 \x01(\tR\n" +
	"extensions\x126\n" +
	"\x17user_management_enabled\x18\x1a \x01(\bR\x15userManagementEnabled\x126\n" +
	"\x17role_management_enabled\x18\x1b \x01(\bR\x15roleManagementEnabled\x12\x1f\n" +
	"\vmcs_enabled\x18\x1c \x01(\bR\n" +
	"mcsEnabled\x128\n" +
	"\x18volume_expansion_enabled\x18\x1d \x01(\bR\x16volumeExpansionEnabled\x12\xaa\x01\n" +
	"\fdistribution\x18\x1e \x01(\tB\x85\x01\x92A\x81\x012fPostgreSQL distribution running in the cluster. Empty string means unknown (e.g. no running pods yet).\xf2\x02\x00\xf2\x02\apercona\xf2\x02\tcommunityR\fdistribution\"+\n" +
	"\x0fMetadataRequest\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\"\xb6\x01\n" +
	"\aVersion\x12\x1d\n" +
	"\n" +
	"image_path\x18\x01 \x01(\tR\timagePath\x12\x1d\n" +
	"\n" +
	"image_hash\x18\x02 \x01(\tR\timageHash\x12(\n" +
	"\x10image_hash_arm64\x18\x03 \x01(\tR\x0eimageHashArm64\x12'\n" +
	"\x06status\x18\x04 \x01(\x0e2\x0f.version.StatusR\x06status\x12\x1a\n" +
	"\bcritical\x18\x05 \x01(\bR\bcritical\"\x8c\x02\n" +
	"\tVersionV2\x12\x1d\n" +
	"\n" +
	"image_path\x18\x01 \x01(\tR\timagePath\x12\x1d\n" +
	"\n" +
	"image_hash\x18\x02 \x01(\tR\timageHash\x12(\n" +
	"\x10image_hash_arm64\x18\x03 \x01(\tR\x0eimageHashArm64\x12R\n" +
	"\x17image_release_timestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x15imageReleaseTimestamp\x12'\n" +
	"\x06status\x18\x04 \x01(\x0e2\x0f.version.StatusR\x06status\x12\x1a\n" +
	"\bcritical\x18\x05 \x01(\bR\bcritical\"\x81#\n" +
	"\rVersionMatrix\x12:\n" +
	"\x06mongod\x18\x01 \x03(\v2\".version.VersionMatrix.MongodEntryR\x06mongod\x121\n" +
	"\x03pxc\x18\x02 \x03(\v2\x1f.version.VersionMatrix.PxcEntryR\x03pxc\x121\n" +
	"\x03pmm\x18\x03 \x03(\v2\x1f.version.VersionMatrix.PmmEntryR\x03pmm\x12@\n" +
	"\bproxysql\x18\x04 \x03(\v2$.version.VersionMatrix.ProxysqlEntryR\bproxysql\x12=\n" +
	"\ahaproxy\x18\x05 \x03(\v2#.version.VersionMatrix.HaproxyEntryR\ahaproxy\x12:\n" +
	"\x06backup\x18\x06 \x03(\v2\".version.VersionMatrix.BackupEntryR\x06backup\x12@\n" +
	"\boperator\x18\a \x03(\v2$.version.VersionMatrix.OperatorEntryR\boperator\x12M\n" +
	"\rlog_collector\x18\b \x03(\v2(.version.VersionMatrix.LogCollectorEntryR\flogCollector\x12F\n" +
	"\n" +
	"postgresql\x18\t \x03(\v2&.version.VersionMatrix.PostgresqlEntryR\n" +
	"postgresql\x12F\n" +
	"\n" +
	"pgbackrest\x18\n" +
	" \x03(\v2&.version.VersionMatrix.PgbackrestEntryR\n" +
	"pgbackrest\x12S\n" +
	"\x0fpgbackrest_repo\x18\v \x03(\v2*.version.VersionMatrix.PgbackrestRepoEntryR\x0epgbackrestRepo\x12@\n" +
	"\bpgbadger\x18\f \x03(\v2$.version.VersionMatrix.PgbadgerEntryR\bpgbadger\x12C\n" +
	"\tpgbouncer\x18\r \x03(\v2%.version.VersionMatrix.PgbouncerEntryR\tpgbouncer\x12J\n" +
	"\fpxc_operator\x18\x0e \x03(\v2'.version.VersionMatrix.PxcOperatorEntryR\vpxcOperator\x12P\n" +
	"\x0epsmdb_operator\x18\x0f \x03(\v2).version.VersionMatrix.PsmdbOperatorEntryR\rpsmdbOperator\x12c\n" +
	"\x15pg_operator_apiserver\x18\x10 \x03(\v2/.version.VersionMatrix.PgOperatorApiserverEntryR\x13pgOperatorApiserver\x12W\n" +
	"\x11pg_operator_event\x18\x11 \x03(\v2+.version.VersionMatrix.PgOperatorEventEntryR\x0fpgOperatorEvent\x12Z\n" +
	"\x12pg_operator_rmdata\x18\x12 \x03(\v2,.version.VersionMatrix.PgOperatorRmdataEntryR\x10pgOperatorRmdata\x12c\n" +
	"\x15pg_operator_scheduler\x18\x13 \x03(\v2/.version.VersionMatrix.PgOperatorSchedulerEntryR\x13pgOperatorScheduler\x12G\n" +
	"\vpg_operator\x18\x14 \x03(\v2&.version.VersionMatrix.PgOperatorEntryR\n" +
	"pgOperator\x12`\n" +
	"\x14pg_operator_deployer\x18\x15 \x03(\v2..version.VersionMatrix.PgOperatorDeployerEntryR\x12pgOperatorDeployer\x12G\n" +
	"\vps_operator\x18\x16 \x03(\v2&.version.VersionMatrix.PsOperatorEntryR\n" +
	"psOperator\x127\n" +
	"\x05mysql\x18\x17 \x03(\v2!.version.VersionMatrix.MysqlEntryR\x05mysql\x12:\n" +
	"\x06router\x18\x18 \x03(\v2\".version.VersionMatrix.RouterEntryR\x06router\x12L\n" +
	"\forchestrator\x18\x19 \x03(\v2(.version.VersionMatrix.OrchestratorEntryR\forchestrator\x12=\n" +
	"\atoolkit\x18\x1a \x03(\v2#.version.VersionMatrix.ToolkitEntryR\atoolkit\x12=\n" +
	"\apostgis\x18\x1b \x03(\v2#.version.VersionMatrix.PostgisEntryR\apostgis\x12M\n" +
	"\rbinlog_server\x18\x1c \x03(\v2(.version.VersionMatrix.BinlogServerEntryR\fbinlogServer\x12C\n" +
	"\tpgupgrade\x18\x1d \x03(\v2%.version.VersionMatrix.PgupgradeEntryR\tpgupgrade\x1aK\n" +
	"\vMongodEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aH\n" +
	"\bPxcEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aH\n" +
	"\bPmmEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aM\n" +
	"\rProxysqlEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aL\n" +
	"\fHaproxyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aK\n" +
	"\vBackupEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aM\n" +
	"\rOperatorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aQ\n" +
	"\x11LogCollectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aO\n" +
	"\x0fPostgresqlEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aO\n" +
	"\x0fPgbackrestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aS\n" +
	"\x13PgbackrestRepoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aM\n" +
	"\rPgbadgerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aN\n" +
	"\x0ePgbouncerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aP\n" +
	"\x10PxcOperatorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aR\n" +
	"\x12PsmdbOperatorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aX\n" +
	"\x18PgOperatorApiserverEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aT\n" +
	"\x14PgOperatorEventEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aU\n" +
	"\x15PgOperatorRmdataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aX\n" +
	"\x18PgOperatorSchedulerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aO\n" +
	"\x0fPgOperatorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aW\n" +
	"\x17PgOperatorDeployerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aO\n" +
	"\x0fPsOperatorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aJ\n" +
	"\n" +
	"MysqlEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aK\n" +
	"\vRouterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aQ\n" +
	"\x11OrchestratorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aL\n" +
	"\fToolkitEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aL\n" +
	"\fPostgisEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aQ\n" +
	"\x11BinlogServerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\x1aN\n" +
	"\x0ePgupgradeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.version.VersionR\x05value:\x028\x01\"w\n" +
	"\x0fOperatorVersion\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12.\n" +
	"\x06matrix\x18\x03 \x01(\v2\x16.version.VersionMatrixR\x06matrix\"G\n" +
	"\x0fVersionResponse\x124\n" +
	"\bversions\x18\x01 \x03(\v2\x18.version.OperatorVersionR\bversions\"H\n" +
	"\x10OperatorResponse\x124\n" +
	"\bversions\x18\x01 \x03(\v2\x18.version.OperatorVersionR\bversions\"G\n" +
	"\x0fProductResponse\x124\n" +
	"\bversions\x18\x01 \x03(\v2\x18.version.OperatorVersionR\bversions\"\xbd\x02\n" +
	"\x0fMetadataVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12K\n" +
	"\vrecommended\x18\x02 \x03(\v2).version.MetadataVersion.RecommendedEntryR\vrecommended\x12E\n" +
	"\tsupported\x18\x03 \x03(\v2'.version.MetadataVersion.SupportedEntryR\tsupported\x1a>\n" +
	"\x10RecommendedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eSupportedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x02\n" +
	"\x11MetadataV2Version\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12M\n" +
	"\vrecommended\x18\x02 \x03(\v2+.version.MetadataV2Version.RecommendedEntryR\vrecommended\x12G\n" +
	"\tsupported\x18\x03 \x03(\v2).version.MetadataV2Version.SupportedEntryR\tsupported\x121\n" +
	"\n" +
	"image_info\x18\x04 \x01(\v2\x12.version.VersionV2R\timageInfo\x1a>\n" +
	"\x10RecommendedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eSupportedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x10MetadataResponse\x124\n" +
	"\bversions\x18\x01 \x03(\v2\x18.version.MetadataVersionR\bversions\"L\n" +
	"\x12MetadataV2Response\x126\n" +
	"\bversions\x18\x01 \x03(\v2\x1a.version.MetadataV2VersionR\bversions\"L\n" +
	"\x16GetReleaseNotesRequest\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"p\n" +
	"\x17GetReleaseNotesResponse\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\frelease_note\x18\x03 \x01(\tR\vreleaseNote*X\n" +
	"\x06Status\x12\x12\n" +
	"\x0estatus_invalid\x10\x00\x12\x0f\n" +
	"\vrecommended\x10\x01\x12\r\n" +
	"\tavailable\x10\x02\x12\f\n" +
	"\brequired\x10\x03\x12\f\n" +
	"\bdisabled\x10\x042\xa9\t\n" +
	"\x0eVersionService\x12\xa9\x01\n" +
	"\x05Apply\x12\x15.version.ApplyRequest\x1a\x18.version.VersionResponse\"o\x92A3\x12\x10Specific version\x1a\x1fReturn specific product version\x82\xd3\xe4\x93\x023\x121/versions/v1/{product}/{operator_version}/{apply}\x12\xd5\x01\n" +
	"\bOperator\x12\x18.version.OperatorRequest\x1a\x19.version.OperatorResponse\"\x93\x01\x92A_\x12.Product versions for specific operator version\x1a-Return product versions for specific operator\x82\xd3\xe4\x93\x02+\x12)/versions/v1/{product}/{operator_version}\x12\xb4\x01\n" +
	"\aProduct\x12\x17.version.ProductRequest\x1a\x18.version.ProductResponse\"v\x92AU\x12)Product versions for all operator version\x1a(Return product versions for all operator\x82\xd3\xe4\x93\x02\x18\x12\x16/versions/v1/{product}\x12\xa5\x01\n" +
	"\bMetadata\x12\x18.version.MetadataRequest\x1a\x19.version.MetadataResponse\"d\x92AC\x12\x16Metadata for a product\x1a)Return metadata information for a product\x82\xd3\xe4\x93\x02\x18\x12\x16/metadata/v1/{product}\x12\xcf\x01\n" +
	"\n" +
	"MetadataV2\x12\x18.version.MetadataRequest\x1a\x1b.version.MetadataV2Response\"\x89\x01\x92Ah\x12\x19v2 metadata for a product\x1aKReturn metadata information with additional image information for a product\x82\xd3\xe4\x93\x02\x18\x12\x16/metadata/v2/{product}\x12\xe1\x01\n" +
	"\x0fGetReleaseNotes\x12\x1f.version.GetReleaseNotesRequest\x1a .version.GetReleaseNotesResponse\"\x8a\x01\x92AZ\x12,Gets the release notes for a product version\x1a*Return release notes for a product version\x82\xd3\xe4\x93\x02'\x12%/release-notes/v1/{product}/{version}B\xaa\x03\x92A\x97\x02\x12\x052\x031.0*\x02\x01\x02r\x89\x02\n" +
	"\xce\x01This service provides version information and image paths for supporting the use of Percona Kubernetes Operators in a variety of scenarios while enabling specific version deployments and automated upgrades.\x126https://github.com/Percona-Lab/percona-version-service\n" +
	"\vcom.versionB\fVersionProtoP\x01Z6github.com/Percona-Lab/percona-version-service/version\xa2\x02\x03VXX\xaa\x02\aVersion\xca\x02\aVersion\xe2\x02\x13Version\\GPBMetadata\xea\x02\aVersionb\x06proto3"

var (
	file_api_version_proto_rawDescOnce sync.Once
	file_api_version_proto_rawDescData []byte
)

func file_api_version_proto_rawDescGZIP() []byte {
	file_api_version_proto_rawDescOnce.Do(func() {
		file_api_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_version_proto_rawDesc), len(file_api_version_proto_rawDesc)))
	})
	return file_api_version_proto_rawDescData
}

var file_api_version_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_version_proto_msgTypes = make([]protoimpl.MessageInfo, 50)
var file_api_version_proto_goTypes = []any{
	(Status)(0),                     // 0: version.Status
	(*ApplyRequest)(nil),            // 1: version.ApplyRequest
	(*OperatorRequest)(nil),         // 2: version.OperatorRequest
	(*ProductRequest)(nil),          // 3: version.ProductRequest
	(*MetadataRequest)(nil),         // 4: version.MetadataRequest
	(*Version)(nil),                 // 5: version.Version
	(*VersionV2)(nil),               // 6: version.VersionV2
	(*VersionMatrix)(nil),           // 7: version.VersionMatrix
	(*OperatorVersion)(nil),         // 8: version.OperatorVersion
	(*VersionResponse)(nil),         // 9: version.VersionResponse
	(*OperatorResponse)(nil),        // 10: version.OperatorResponse
	(*ProductResponse)(nil),         // 11: version.ProductResponse
	(*MetadataVersion)(nil),         // 12: version.MetadataVersion
	(*MetadataV2Version)(nil),       // 13: version.MetadataV2Version
	(*MetadataResponse)(nil),        // 14: version.MetadataResponse
	(*MetadataV2Response)(nil),      // 15: version.MetadataV2Response
	(*GetReleaseNotesRequest)(nil),  // 16: version.GetReleaseNotesRequest
	(*GetReleaseNotesResponse)(nil), // 17: version.GetReleaseNotesResponse
	nil,                             // 18: version.VersionMatrix.MongodEntry
	nil,                             // 19: version.VersionMatrix.PxcEntry
	nil,                             // 20: version.VersionMatrix.PmmEntry
	nil,                             // 21: version.VersionMatrix.ProxysqlEntry
	nil,                             // 22: version.VersionMatrix.HaproxyEntry
	nil,                             // 23: version.VersionMatrix.BackupEntry
	nil,                             // 24: version.VersionMatrix.OperatorEntry
	nil,                             // 25: version.VersionMatrix.LogCollectorEntry
	nil,                             // 26: version.VersionMatrix.PostgresqlEntry
	nil,                             // 27: version.VersionMatrix.PgbackrestEntry
	nil,                             // 28: version.VersionMatrix.PgbackrestRepoEntry
	nil,                             // 29: version.VersionMatrix.PgbadgerEntry
	nil,                             // 30: version.VersionMatrix.PgbouncerEntry
	nil,                             // 31: version.VersionMatrix.PxcOperatorEntry
	nil,                             // 32: version.VersionMatrix.PsmdbOperatorEntry
	nil,                             // 33: version.VersionMatrix.PgOperatorApiserverEntry
	nil,                             // 34: version.VersionMatrix.PgOperatorEventEntry
	nil,                             // 35: version.VersionMatrix.PgOperatorRmdataEntry
	nil,                             // 36: version.VersionMatrix.PgOperatorSchedulerEntry
	nil,                             // 37: version.VersionMatrix.PgOperatorEntry
	nil,                             // 38: version.VersionMatrix.PgOperatorDeployerEntry
	nil,                             // 39: version.VersionMatrix.PsOperatorEntry
	nil,                             // 40: version.VersionMatrix.MysqlEntry
	nil,                             // 41: version.VersionMatrix.RouterEntry
	nil,                             // 42: version.VersionMatrix.OrchestratorEntry
	nil,                             // 43: version.VersionMatrix.ToolkitEntry
	nil,                             // 44: version.VersionMatrix.PostgisEntry
	nil,                             // 45: version.VersionMatrix.BinlogServerEntry
	nil,                             // 46: version.VersionMatrix.PgupgradeEntry
	nil,                             // 47: version.MetadataVersion.RecommendedEntry
	nil,                             // 48: version.MetadataVersion.SupportedEntry
	nil,                             // 49: version.MetadataV2Version.RecommendedEntry
	nil,                             // 50: version.MetadataV2Version.SupportedEntry
	(*timestamppb.Timestamp)(nil),   // 51: google.protobuf.Timestamp
}
var file_api_version_proto_depIdxs = []int32{
	0,  // 0: version.Version.status:type_name -> version.Status
	51, // 1: version.VersionV2.image_release_timestamp:type_name -> google.protobuf.Timestamp
	0,  // 2: version.VersionV2.status:type_name -> version.Status
	18, // 3: version.VersionMatrix.mongod:type_name -> version.VersionMatrix.MongodEntry
	19, // 4: version.VersionMatrix.pxc:type_name -> version.VersionMatrix.PxcEntry
	20, // 5: version.VersionMatrix.pmm:type_name -> version.VersionMatrix.PmmEntry
	21, // 6: version.VersionMatrix.proxysql:type_name -> version.VersionMatrix.ProxysqlEntry
	22, // 7: version.VersionMatrix.haproxy:type_name -> version.VersionMatrix.HaproxyEntry
	23, // 8: version.VersionMatrix.backup:type_name -> version.VersionMatrix.BackupEntry
	24, // 9: version.VersionMatrix.operator:type_name -> version.VersionMatrix.OperatorEntry
	25, // 10: version.VersionMatrix.log_collector:type_name -> version.VersionMatrix.LogCollectorEntry
	26, // 11: version.VersionMatrix.postgresql:type_name -> version.VersionMatrix.PostgresqlEntry
	27, // 12: version.VersionMatrix.pgbackrest:type_name -> version.VersionMatrix.PgbackrestEntry
	28, // 13: version.VersionMatrix.pgbackrest_repo:type_name -> version.VersionMatrix.PgbackrestRepoEntry
	29, // 14: version.VersionMatrix.pgbadger:type_name -> version.VersionMatrix.PgbadgerEntry
	30, // 15: version.VersionMatrix.pgbouncer:type_name -> version.VersionMatrix.PgbouncerEntry
	31, // 16: version.VersionMatrix.pxc_operator:type_name -> version.VersionMatrix.PxcOperatorEntry
	32, // 17: version.VersionMatrix.psmdb_operator:type_name -> version.VersionMatrix.PsmdbOperatorEntry
	33, // 18: version.VersionMatrix.pg_operator_apiserver:type_name -> version.VersionMatrix.PgOperatorApiserverEntry
	34, // 19: version.VersionMatrix.pg_operator_event:type_name -> version.VersionMatrix.PgOperatorEventEntry
	35, // 20: version.VersionMatrix.pg_operator_rmdata:type_name -> version.VersionMatrix.PgOperatorRmdataEntry
	36, // 21: version.VersionMatrix.pg_operator_scheduler:type_name -> version.VersionMatrix.PgOperatorSchedulerEntry
	37, // 22: version.VersionMatrix.pg_operator:type_name -> version.VersionMatrix.PgOperatorEntry
	38, // 23: version.VersionMatrix.pg_operator_deployer:type_name -> version.VersionMatrix.PgOperatorDeployerEntry
	39, // 24: version.VersionMatrix.ps_operator:type_name -> version.VersionMatrix.PsOperatorEntry
	40, // 25: version.VersionMatrix.mysql:type_name -> version.VersionMatrix.MysqlEntry
	41, // 26: version.VersionMatrix.router:type_name -> version.VersionMatrix.RouterEntry
	42, // 27: version.VersionMatrix.orchestrator:type_name -> version.VersionMatrix.OrchestratorEntry
	43, // 28: version.VersionMatrix.toolkit:type_name -> version.VersionMatrix.ToolkitEntry
	44, // 29: version.VersionMatrix.postgis:type_name -> version.VersionMatrix.PostgisEntry
	45, // 30: version.VersionMatrix.binlog_server:type_name -> version.VersionMatrix.BinlogServerEntry
	46, // 31: version.VersionMatrix.pgupgrade:type_name -> version.VersionMatrix.PgupgradeEntry
	7,  // 32: version.OperatorVersion.matrix:type_name -> version.VersionMatrix
	8,  // 33: version.VersionResponse.versions:type_name -> version.OperatorVersion
	8,  // 34: version.OperatorResponse.versions:type_name -> version.OperatorVersion
	8,  // 35: version.ProductResponse.versions:type_name -> version.OperatorVersion
	47, // 36: version.MetadataVersion.recommended:type_name -> version.MetadataVersion.RecommendedEntry
	48, // 37: version.MetadataVersion.supported:type_name -> version.MetadataVersion.SupportedEntry
	49, // 38: version.MetadataV2Version.recommended:type_name -> version.MetadataV2Version.RecommendedEntry
	50, // 39: version.MetadataV2Version.supported:type_name -> version.MetadataV2Version.SupportedEntry
	6,  // 40: version.MetadataV2Version.image_info:type_name -> version.VersionV2
	12, // 41: version.MetadataResponse.versions:type_name -> version.MetadataVersion
	13, // 42: version.MetadataV2Response.versions:type_name -> version.MetadataV2Version
	5,  // 43: version.VersionMatrix.MongodEntry.value:type_name -> version.Version
	5,  // 44: version.VersionMatrix.PxcEntry.value:type_name -> version.Version
	5,  // 45: version.VersionMatrix.PmmEntry.value:type_name -> version.Version
	5,  // 46: version.VersionMatrix.ProxysqlEntry.value:type_name -> version.Version
	5,  // 47: version.VersionMatrix.HaproxyEntry.value:type_name -> version.Version
	5,  // 48: version.VersionMatrix.BackupEntry.value:type_name -> version.Version
	5,  // 49: version.VersionMatrix.OperatorEntry.value:type_name -> version.Version
	5,  // 50: version.VersionMatrix.LogCollectorEntry.value:type_name -> version.Version
	5,  // 51: version.VersionMatrix.PostgresqlEntry.value:type_name -> version.Version
	5,  // 52: version.VersionMatrix.PgbackrestEntry.value:type_name -> version.Version
	5,  // 53: version.VersionMatrix.PgbackrestRepoEntry.value:type_name -> version.Version
	5,  // 54: version.VersionMatrix.PgbadgerEntry.value:type_name -> version.Version
	5,  // 55: version.VersionMatrix.PgbouncerEntry.value:type_name -> version.Version
	5,  // 56: version.VersionMatrix.PxcOperatorEntry.value:type_name -> version.Version
	5,  // 57: version.VersionMatrix.PsmdbOperatorEntry.value:type_name -> version.Version
	5,  // 58: version.VersionMatrix.PgOperatorApiserverEntry.value:type_name -> version.Version
	5,  // 59: version.VersionMatrix.PgOperatorEventEntry.value:type_name -> version.Version
	5,  // 60: version.VersionMatrix.PgOperatorRmdataEntry.value:type_name -> version.Version
	5,  // 61: version.VersionMatrix.PgOperatorSchedulerEntry.value:type_name -> version.Version
	5,  // 62: version.VersionMatrix.PgOperatorEntry.value:type_name -> version.Version
	5,  // 63: version.VersionMatrix.PgOperatorDeployerEntry.value:type_name -> version.Version
	5,  // 64: version.VersionMatrix.PsOperatorEntry.value:type_name -> version.Version
	5,  // 65: version.VersionMatrix.MysqlEntry.value:type_name -> version.Version
	5,  // 66: version.VersionMatrix.RouterEntry.value:type_name -> version.Version
	5,  // 67: version.VersionMatrix.OrchestratorEntry.value:type_name -> version.Version
	5,  // 68: version.VersionMatrix.ToolkitEntry.value:type_name -> version.Version
	5,  // 69: version.VersionMatrix.PostgisEntry.value:type_name -> version.Version
	5,  // 70: version.VersionMatrix.BinlogServerEntry.value:type_name -> version.Version
	5,  // 71: version.VersionMatrix.PgupgradeEntry.value:type_name -> version.Version
	1,  // 72: version.VersionService.Apply:input_type -> version.ApplyRequest
	2,  // 73: version.VersionService.Operator:input_type -> version.OperatorRequest
	3,  // 74: version.VersionService.Product:input_type -> version.ProductRequest
	4,  // 75: version.VersionService.Metadata:input_type -> version.MetadataRequest
	4,  // 76: version.VersionService.MetadataV2:input_type -> version.MetadataRequest
	16, // 77: version.VersionService.GetReleaseNotes:input_type -> version.GetReleaseNotesRequest
	9,  // 78: version.VersionService.Apply:output_type -> version.VersionResponse
	10, // 79: version.VersionService.Operator:output_type -> version.OperatorResponse
	11, // 80: version.VersionService.Product:output_type -> version.ProductResponse
	14, // 81: version.VersionService.Metadata:output_type -> version.MetadataResponse
	15, // 82: version.VersionService.MetadataV2:output_type -> version.MetadataV2Response
	17, // 83: version.VersionService.GetReleaseNotes:output_type -> version.GetReleaseNotesResponse
	78, // [78:84] is the sub-list for method output_type
	72, // [72:78] is the sub-list for method input_type
	72, // [72:72] is the sub-list for extension type_name
	72, // [72:72] is the sub-list for extension extendee
	0,  // [0:72] is the sub-list for field type_name
}

func init() { file_api_version_proto_init() }
func file_api_version_proto_init() {
	if File_api_version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_version_proto_rawDesc), len(file_api_version_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   50,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_version_proto_goTypes,
		DependencyIndexes: file_api_version_proto_depIdxs,
		EnumInfos:         file_api_version_proto_enumTypes,
		MessageInfos:      file_api_version_proto_msgTypes,
	}.Build()
	File_api_version_proto = out.File
	file_api_version_proto_goTypes = nil
	file_api_version_proto_depIdxs = nil
}
