// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExampleOperatorVersion example operator version
//
// swagger:model exampleOperatorVersion
type ExampleOperatorVersion struct {

	// database
	Database string `json:"database,omitempty"`

	// matrix
	Matrix *ExampleVersionMatrix `json:"matrix,omitempty"`

	// operator
	Operator string `json:"operator,omitempty"`
}

// Validate validates this example operator version
func (m *ExampleOperatorVersion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMatrix(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExampleOperatorVersion) validateMatrix(formats strfmt.Registry) error {

	if swag.IsZero(m.Matrix) { // not required
		return nil
	}

	if m.Matrix != nil {
		if err := m.Matrix.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("matrix")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExampleOperatorVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExampleOperatorVersion) UnmarshalBinary(b []byte) error {
	var res ExampleOperatorVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
