// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExampleVersion example version
//
// swagger:model exampleVersion
type ExampleVersion struct {

	// critilal
	Critilal bool `json:"critilal,omitempty"`

	// imagehash
	Imagehash string `json:"imagehash,omitempty"`

	// imagepath
	Imagepath string `json:"imagepath,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this example version
func (m *ExampleVersion) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExampleVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExampleVersion) UnmarshalBinary(b []byte) error {
	var res ExampleVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
