swagger: "2.0"
info:
  title: api/version.proto
  version: "1.0"
tags:
  - name: VersionService
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /metadata/v1/{product}:
    get:
      summary: Metadata for a product
      description: Return metadata information for a product
      operationId: VersionService_Metadata
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/versionMetadataResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: product
          in: path
          required: true
          type: string
      tags:
        - VersionService
  /release-notes/v1/{product}/{version}:
    get:
      summary: Gets the release notes for a product version
      description: Return release notes for a product version
      operationId: VersionService_GetReleaseNotes
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/versionGetReleaseNotesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: product
          description: Product name.
          in: path
          required: true
          type: string
        - name: version
          description: Product version.
          in: path
          required: true
          type: string
      tags:
        - VersionService
  /versions/v1/{product}:
    get:
      summary: Product versions for all operator version
      description: Return product versions for all operator
      operationId: VersionService_Product
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/versionProductResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: product
          in: path
          required: true
          type: string
        - name: databaseVersion
          in: query
          required: false
          type: string
        - name: kubeVersion
          in: query
          required: false
          type: string
        - name: platform
          in: query
          required: false
          type: string
        - name: pmmVersion
          in: query
          required: false
          type: string
        - name: backupVersion
          in: query
          required: false
          type: string
        - name: proxysqlVersion
          in: query
          required: false
          type: string
        - name: haproxyVersion
          in: query
          required: false
          type: string
        - name: namespaceUid
          in: query
          required: false
          type: string
        - name: customResourceUid
          in: query
          required: false
          type: string
        - name: logCollectorVersion
          in: query
          required: false
          type: string
        - name: shardingEnabled
          in: query
          required: false
          type: boolean
        - name: hashicorpVaultEnabled
          in: query
          required: false
          type: boolean
        - name: clusterWideEnabled
          in: query
          required: false
          type: boolean
        - name: pmmEnabled
          in: query
          required: false
          type: boolean
        - name: helmDeployOperator
          in: query
          required: false
          type: boolean
        - name: helmDeployCr
          in: query
          required: false
          type: boolean
        - name: sidecarsUsed
          in: query
          required: false
          type: boolean
        - name: backupsEnabled
          in: query
          required: false
          type: boolean
        - name: clusterSize
          in: query
          required: false
          type: integer
          format: int32
        - name: pitrEnabled
          in: query
          required: false
          type: boolean
        - name: physicalBackupScheduled
          in: query
          required: false
          type: boolean
        - name: extensions
          in: query
          required: false
          type: string
        - name: userManagementEnabled
          in: query
          required: false
          type: boolean
        - name: roleManagementEnabled
          in: query
          required: false
          type: boolean
        - name: mcsEnabled
          in: query
          required: false
          type: boolean
        - name: volumeExpansionEnabled
          in: query
          required: false
          type: boolean
      tags:
        - VersionService
  /versions/v1/{product}/{operatorVersion}:
    get:
      summary: Product versions for specific operator version
      description: Return product versions for specific operator
      operationId: VersionService_Operator
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/versionOperatorResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: product
          in: path
          required: true
          type: string
        - name: operatorVersion
          in: path
          required: true
          type: string
        - name: databaseVersion
          in: query
          required: false
          type: string
        - name: kubeVersion
          in: query
          required: false
          type: string
        - name: platform
          in: query
          required: false
          type: string
        - name: pmmVersion
          in: query
          required: false
          type: string
        - name: backupVersion
          in: query
          required: false
          type: string
        - name: proxysqlVersion
          in: query
          required: false
          type: string
        - name: haproxyVersion
          in: query
          required: false
          type: string
        - name: namespaceUid
          in: query
          required: false
          type: string
        - name: customResourceUid
          in: query
          required: false
          type: string
        - name: logCollectorVersion
          in: query
          required: false
          type: string
        - name: shardingEnabled
          in: query
          required: false
          type: boolean
        - name: hashicorpVaultEnabled
          in: query
          required: false
          type: boolean
        - name: clusterWideEnabled
          in: query
          required: false
          type: boolean
        - name: pmmEnabled
          in: query
          required: false
          type: boolean
        - name: helmDeployOperator
          in: query
          required: false
          type: boolean
        - name: helmDeployCr
          in: query
          required: false
          type: boolean
        - name: sidecarsUsed
          in: query
          required: false
          type: boolean
        - name: backupsEnabled
          in: query
          required: false
          type: boolean
        - name: clusterSize
          in: query
          required: false
          type: integer
          format: int32
        - name: pitrEnabled
          in: query
          required: false
          type: boolean
        - name: physicalBackupScheduled
          in: query
          required: false
          type: boolean
        - name: extensions
          in: query
          required: false
          type: string
        - name: userManagementEnabled
          in: query
          required: false
          type: boolean
        - name: roleManagementEnabled
          in: query
          required: false
          type: boolean
        - name: mcsEnabled
          in: query
          required: false
          type: boolean
        - name: volumeExpansionEnabled
          in: query
          required: false
          type: boolean
      tags:
        - VersionService
  /versions/v1/{product}/{operatorVersion}/{apply}:
    get:
      summary: Specific version
      description: Return specific product version
      operationId: VersionService_Apply
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/versionVersionResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: product
          in: path
          required: true
          type: string
        - name: operatorVersion
          in: path
          required: true
          type: string
        - name: apply
          in: path
          required: true
          type: string
        - name: databaseVersion
          in: query
          required: false
          type: string
        - name: kubeVersion
          in: query
          required: false
          type: string
        - name: platform
          in: query
          required: false
          type: string
        - name: pmmVersion
          in: query
          required: false
          type: string
        - name: backupVersion
          in: query
          required: false
          type: string
        - name: proxysqlVersion
          in: query
          required: false
          type: string
        - name: haproxyVersion
          in: query
          required: false
          type: string
        - name: namespaceUid
          in: query
          required: false
          type: string
        - name: customResourceUid
          in: query
          required: false
          type: string
        - name: logCollectorVersion
          in: query
          required: false
          type: string
        - name: shardingEnabled
          in: query
          required: false
          type: boolean
        - name: hashicorpVaultEnabled
          in: query
          required: false
          type: boolean
        - name: clusterWideEnabled
          in: query
          required: false
          type: boolean
        - name: pmmEnabled
          in: query
          required: false
          type: boolean
        - name: helmDeployOperator
          in: query
          required: false
          type: boolean
        - name: helmDeployCr
          in: query
          required: false
          type: boolean
        - name: sidecarsUsed
          in: query
          required: false
          type: boolean
        - name: backupsEnabled
          in: query
          required: false
          type: boolean
        - name: clusterSize
          in: query
          required: false
          type: integer
          format: int32
        - name: pitrEnabled
          in: query
          required: false
          type: boolean
        - name: physicalBackupScheduled
          in: query
          required: false
          type: boolean
        - name: extensions
          in: query
          required: false
          type: string
        - name: userManagementEnabled
          in: query
          required: false
          type: boolean
        - name: roleManagementEnabled
          in: query
          required: false
          type: boolean
        - name: mcsEnabled
          in: query
          required: false
          type: boolean
        - name: volumeExpansionEnabled
          in: query
          required: false
          type: boolean
      tags:
        - VersionService
definitions:
  googlerpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  versionGetReleaseNotesResponse:
    type: object
    properties:
      product:
        type: string
        description: The product name.
      version:
        type: string
      releaseNote:
        type: string
        description: release_notes is the release note for this version.
  versionMetadataResponse:
    type: object
    properties:
      versions:
        type: array
        items:
          type: object
          $ref: '#/definitions/versionMetadataVersion'
  versionMetadataVersion:
    type: object
    properties:
      version:
        type: string
      recommended:
        type: object
        additionalProperties:
          type: string
        description: Recommended is the recommended version for a given component.
      supported:
        type: object
        additionalProperties:
          type: string
        description: Supported holds semver constraint per component, such as ">= 1.0, < 1.4".
      imageInfo:
        $ref: '#/definitions/versionVersion'
        description: ImageInfo holds information about the docker image for this version.
    description: MetadataVersion represents metadata for a given version.
  versionOperatorResponse:
    type: object
    properties:
      versions:
        type: array
        items:
          type: object
          $ref: '#/definitions/versionOperatorVersion'
  versionOperatorVersion:
    type: object
    properties:
      product:
        type: string
      operator:
        type: string
      matrix:
        $ref: '#/definitions/versionVersionMatrix'
    description: OperatorVersion represents operator version.
  versionProductResponse:
    type: object
    properties:
      versions:
        type: array
        items:
          type: object
          $ref: '#/definitions/versionOperatorVersion'
  versionStatus:
    type: string
    enum:
      - status_invalid
      - recommended
      - available
      - required
      - disabled
    default: status_invalid
    description: Status describes the current version status.
  versionVersion:
    type: object
    properties:
      imagePath:
        type: string
      imageHash:
        type: string
      imageHashArm64:
        type: string
      imageReleaseTimestamp:
        type: string
        format: date-time
        description: release_timestamp is the release time of this image.
      status:
        $ref: '#/definitions/versionStatus'
      critical:
        type: boolean
    description: Version represents product version information.
  versionVersionMatrix:
    type: object
    properties:
      mongod:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      pxc:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      pmm:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      proxysql:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      haproxy:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      backup:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      operator:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      logCollector:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      postgresql:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      pgbackrest:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      pgbackrestRepo:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      pgbadger:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      pgbouncer:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      pxcOperator:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      psmdbOperator:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      pgOperatorApiserver:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      pgOperatorEvent:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      pgOperatorRmdata:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      pgOperatorScheduler:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      pgOperator:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      pgOperatorDeployer:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      psOperator:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      mysql:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      router:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      orchestrator:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      toolkit:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
      postgis:
        type: object
        additionalProperties:
          $ref: '#/definitions/versionVersion'
    description: VersionMatrix represents set of possible product versions.
  versionVersionResponse:
    type: object
    properties:
      versions:
        type: array
        items:
          type: object
          $ref: '#/definitions/versionOperatorVersion'
externalDocs:
  description: This service provides version information and image paths for supporting the use of Percona Kubernetes Operators in a variety of scenarios while enabling specific version deployments and automated upgrades.
  url: https://github.com/Percona-Lab/percona-version-service
